### ISSUE TITLE
Support for async providers

### ISSUE THREAD

**Issue by ytimenkov** [illuin-tech/opyoid#50]
Apparently this library can work quite well not only for constructing objects, but also for calling functions where parameters need to be injected. Something like:

```python

async def func(trio.Nursery n):
   pass

async with trio.open_nursery() as nursery:
    injector = Injector([], [SelfBinding(func, scope=PerLookupScope), InstanceBinding(trio.Nursery, nursery)])
    nursery.start_soon(injector.inject, func)
```

Of course in real case there could be multiple parameters, and `func` is not defined here but loaded via `importlib.metadata.entry_points`. The idea is to start plugins which have different dependencies.

However it would be nice if injector could bind arguments asynchronously. E.g. if signature is `Callable` then invoke it directly, but if it's `Awaitable` or (or `Callable` which returns one) then it should `await` on it to get result.

I can see that this can be also used for async object construction, e.g. if factory function need to do async resolution or wait for some other initialization to complete.

**Comment by Aegdesil** [comment]
I understand the need for async providers, however I think that enabling this would require to duplicate most of the code to be able to run with async/await, since you cannot await outside an async method (and you cannot run an async method without awaiting it).

Unless there is a simple way to do this that I missed, this feature cannot be added to the library.
